### ISSUE TITLE
Is there a trained testable model that can be used to generate jailbreak prompts based on the input knowledge points?

### ISSUE THREAD

**Issue by tcexeexe** [Argithun/Knowledge-to-Jailbreak#1]
If it is not convenient to make public, could you please send me an email?

**Comment by Argithun** [comment]
Thank you for your interest. However, the work related to training the generative model is handled by my collaborator, and I need to obtain their permission. I should be able to get back to you within a week.

**Comment by Argithun** [comment]
> If it is not convenient to make public, could you please send me an email?

Hi, this is where our generator is located: https://huggingface.co/tsq2000/Jailbreak-generator
